# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec0fe984e6c8e0bd801e4c80024d663aee7133e6256e4d63f949fd21fb482729a3565da2d9c40f0d57773b057b34c02c69bd42bfcc032d320abdb9f31c9d7b13

test:
  secret_key_base: aca3ba7521eef35779e6b5a4ac860cc7557828fb1b9486eea033e9858c81187ccaa55daaf902827018143aeddfd1f33973f528168dff56e8f96090719bad215d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
